test-website:
    name: Test WebSite
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebSite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # ТАЗИ СТЪПКА ОПРАВЯ ВЕРСИЯТА И ПРАВАТА
      - name: Force Install Stable Jest
        run: npm install jest@29.7.0 jest-environment-jsdom@29.7.0 --save-dev

      - name: Run WebSite tests
        run: ./node_modules/.bin/jest --env=jsdom
